"""Description pages: one per record, faithful to the record, and linked from the README."""
import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import render_part_pages as pages  # noqa: E402
import render_parts_table as table  # noqa: E402

FICHES = sorted((ROOT / "catalog" / "parts").glob("*.json"))


class PartPageTests(unittest.TestCase):
    def test_one_page_per_catalogue_record(self):
        attendues = pages.attendues()
        descriptions = [c for c in attendues if c.parent.name == "pieces"]
        self.assertEqual(len(descriptions), len(FICHES))
        for chemin in attendues:
            self.assertTrue(chemin.exists(), f"missing page: {chemin.relative_to(ROOT)}")

    def test_each_part_folder_has_a_presentation_page(self):
        for chemin in FICHES:
            fiche = json.loads(chemin.read_text(encoding="utf-8"))
            dossier = ROOT / "parts" / fiche["part_id"].lower()
            if not dossier.is_dir():
                continue
            texte = (dossier / "README.md").read_text(encoding="utf-8")
            self.assertIn(fiche["part_id"], texte)
            self.assertIn("SAFETY.md", texte)
            self.assertIn(f"docs/pieces/{fiche['part_id'].lower()}.md", texte)
            tete = texte.split("## What it is")[0]
            self.assertIn("[!CAUTION]", tete)
            if (dossier / "print" / "print.json").exists():
                # a printable design says so, and still says it is not validated
                self.assertIn("ready to print", tete)
                self.assertIn("not validated", tete)
                self.assertIn("decision 0010", tete)
                self.assertNotIn("not a print file", tete)
            elif (dossier / "print" / "kit.json").exists():
                # a fit-test kit is announced as such, and the part is still said unvalidated
                self.assertIn("fit-test kit is ready to print", tete)
                self.assertIn("not validated", tete)
                self.assertIn("decision 0009", tete)
            else:
                self.assertIn("Not ready to print", tete)
                if (dossier / "media" / "preview.png").exists():
                    self.assertIn("media/preview.png", texte)
                    self.assertIn("not a print file", texte)

    def test_check_passes_on_the_committed_pages(self):
        argv = sys.argv
        sys.argv = ["render_part_pages.py", "--check"]
        try:
            self.assertEqual(pages.main(), 0)
        finally:
            sys.argv = argv

    def test_each_page_cites_its_record_identifier_and_safety(self):
        for chemin in FICHES:
            fiche = json.loads(chemin.read_text(encoding="utf-8"))
            page = ROOT / "docs" / "pieces" / f"{fiche['part_id'].lower()}.md"
            texte = page.read_text(encoding="utf-8")
            self.assertIn(fiche["part_id"], texte)
            self.assertIn(chemin.name, texte, "the page must cite its record")
            self.assertIn("SAFETY.md", texte)
            self.assertIn("generated by scripts/render_part_pages.py", texte)

    def test_readme_links_to_pages_not_to_json(self):
        bloc = table.bloc()
        self.assertNotIn("](catalog/parts/", bloc)
        for chemin in FICHES:
            fiche = json.loads(chemin.read_text(encoding="utf-8"))
            self.assertIn(f"](docs/pieces/{fiche['part_id'].lower()}.md)", bloc)

    def test_drift_is_detected(self):
        chemin, attendu = next(iter(pages.attendues().items()))
        original = chemin.read_text(encoding="utf-8")
        chemin.write_text(original + "\nline added by hand\n", encoding="utf-8")
        argv = sys.argv
        sys.argv = ["render_part_pages.py", "--check"]
        try:
            self.assertEqual(pages.main(), 1)
        finally:
            sys.argv = argv
            chemin.write_text(original, encoding="utf-8")
        self.assertEqual(chemin.read_text(encoding="utf-8"), attendu)


if __name__ == "__main__":
    unittest.main()
