// Generated by scripts/generate_twin_envelope.py; edit the generator or source data.
// This is a reference envelope and datum cage, not a reconstructed Porsche body.
// Coordinate system: X front-to-rear, Y left/right about centreline, Z upward from ground.
// Axle positions are centred in the length only for visualisation; their overhangs are not sourced.

length_mm = 4260; // MNL-TECH-0022, PDF p.19
width_mm = 1735; // MNL-TECH-0023, PDF p.19
height_mm = 1315; // MNL-TECH-0024, PDF p.19
wheelbase_mm = 2272; // MNL-TECH-0026, PDF p.19
front_track_mm = 1405; // MNL-TECH-0027, PDF p.19
rear_track_mm = 1444; // MNL-TECH-0028, PDF p.19
ground_clearance_mm = 120; // MNL-TECH-0029, PDF p.19
display_beam_mm = 2; // visualisation thickness, not a vehicle dimension
front_axle_x = (length_mm - wheelbase_mm) / 2; // visualisation assumption
rear_axle_x = front_axle_x + wheelbase_mm; // visualisation assumption

module beam_x(x, y, z, length) {
    translate([x, y, z]) cube([length, display_beam_mm, display_beam_mm]);
}
module beam_y(x, y, z, length) {
    translate([x, y, z]) cube([display_beam_mm, length, display_beam_mm]);
}
module beam_z(x, y, z, length) {
    translate([x, y, z]) cube([display_beam_mm, display_beam_mm, length]);
}

module envelope_cage() {
    color([0.20, 0.55, 0.95, 0.35]) {
        for (z = [0, height_mm]) for (y = [-width_mm / 2, width_mm / 2])
            beam_x(0, y, z, length_mm);
        for (z = [0, height_mm]) for (x = [0, length_mm])
            beam_y(x, -width_mm / 2, z, width_mm);
        for (x = [0, length_mm]) for (y = [-width_mm / 2, width_mm / 2])
            beam_z(x, y, 0, height_mm);
    }
}

module datum_cage() {
    // The clearance line is a reference plane, not the underside of a body surface.
    color([1.00, 0.70, 0.10, 0.75])
        beam_y(0, -width_mm / 2, ground_clearance_mm, width_mm);
    color([0.90, 0.15, 0.15, 0.85]) {
        beam_y(front_axle_x, -front_track_mm / 2, 0, front_track_mm);
        beam_y(rear_axle_x, -rear_track_mm / 2, 0, rear_track_mm);
    }
}

envelope_cage();
datum_cage();
