#!/usr/bin/env python3
"""Generate the first 3D reference envelope of the Porsche 993 twin.

The output is intentionally a wireframe datum, not a guessed body surface. All
vehicle dimensions are read from the documented-specification record so that a
change in the source data is visible and reproducible.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MEASUREMENTS = ROOT / "catalog" / "measurements" / "MEAS-MANUAL-993-ALL.json"
DEFAULT_SCAD = ROOT / "twin" / "993" / "source" / "reference_envelope.scad"
DEFAULT_MANIFEST = ROOT / "twin" / "993" / "reference-envelope.json"

PARAMETERS = {
    "length_mm": ("overall length", "MNL-TECH-0022"),
    "width_mm": ("overall width", "MNL-TECH-0023"),
    "height_mm": ("overall height", "MNL-TECH-0024"),
    "wheelbase_mm": ("design wheelbase", "MNL-TECH-0026"),
    "front_track_mm": ("front track", "MNL-TECH-0027"),
    "rear_track_mm": ("rear track", "MNL-TECH-0028"),
    "ground_clearance_mm": ("ground clearance", "MNL-TECH-0029"),
}


def load_values(path: Path) -> dict[str, dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {row["value_id"]: row for row in payload["declared_values"]}


def first_number(row: dict[str, Any], value_id: str) -> float:
    values = row.get("numeric_values")
    if not isinstance(values, list) or not values:
        raise ValueError(f"{value_id} has no numeric value")
    value = values[0]
    if not isinstance(value, (int, float)) or isinstance(value, bool) or value <= 0:
        raise ValueError(f"{value_id} has no positive numeric value")
    if "mm" not in str(row.get("unit", "")):
        raise ValueError(f"{value_id} is not declared in millimetres")
    return float(value)


def collect(values: dict[str, dict[str, Any]]) -> tuple[dict[str, float], dict[str, dict[str, Any]]]:
    dimensions: dict[str, float] = {}
    evidence: dict[str, dict[str, Any]] = {}
    for name, (description, value_id) in PARAMETERS.items():
        row = values.get(value_id)
        if row is None:
            raise ValueError(f"missing source measurement {value_id} ({description})")
        dimensions[name] = first_number(row, value_id)
        evidence[name] = {
            "value_id": value_id,
            "pdf_page": row["pdf_page"],
            "value_text": row["value_text"],
            "extraction_status": row["extraction_status"],
        }
    if dimensions["wheelbase_mm"] >= dimensions["length_mm"]:
        raise ValueError("wheelbase must be shorter than overall length")
    if dimensions["ground_clearance_mm"] >= dimensions["height_mm"]:
        raise ValueError("ground clearance must be shorter than overall height")
    return dimensions, evidence


def scad(dimensions: dict[str, float], evidence: dict[str, dict[str, Any]]) -> str:
    def value(name: str) -> str:
        return f"{dimensions[name]:.3f}".rstrip("0").rstrip(".")

    lines = [
        "// Generated by scripts/generate_twin_envelope.py; edit the generator or source data.",
        "// This is a reference envelope and datum cage, not a reconstructed Porsche body.",
        "// Coordinate system: X front-to-rear, Y left/right about centreline, Z upward from ground.",
        "// Axle positions are centred in the length only for visualisation; their overhangs are not sourced.",
        "",
    ]
    for name in PARAMETERS:
        lines.append(f"{name} = {value(name)}; // {evidence[name]['value_id']}, PDF p.{evidence[name]['pdf_page']}")
    lines.extend(
        [
            "display_beam_mm = 2; // visualisation thickness, not a vehicle dimension",
            "front_axle_x = (length_mm - wheelbase_mm) / 2; // visualisation assumption",
            "rear_axle_x = front_axle_x + wheelbase_mm; // visualisation assumption",
            "",
            "module beam_x(x, y, z, length) {",
            "    translate([x, y, z]) cube([length, display_beam_mm, display_beam_mm]);",
            "}",
            "module beam_y(x, y, z, length) {",
            "    translate([x, y, z]) cube([display_beam_mm, length, display_beam_mm]);",
            "}",
            "module beam_z(x, y, z, length) {",
            "    translate([x, y, z]) cube([display_beam_mm, display_beam_mm, length]);",
            "}",
            "",
            "module envelope_cage() {",
            "    color([0.20, 0.55, 0.95, 0.35]) {",
            "        for (z = [0, height_mm]) for (y = [-width_mm / 2, width_mm / 2])",
            "            beam_x(0, y, z, length_mm);",
            "        for (z = [0, height_mm]) for (x = [0, length_mm])",
            "            beam_y(x, -width_mm / 2, z, width_mm);",
            "        for (x = [0, length_mm]) for (y = [-width_mm / 2, width_mm / 2])",
            "            beam_z(x, y, 0, height_mm);",
            "    }",
            "}",
            "",
            "module datum_cage() {",
            "    // The clearance line is a reference plane, not the underside of a body surface.",
            "    color([1.00, 0.70, 0.10, 0.75])",
            "        beam_y(0, -width_mm / 2, ground_clearance_mm, width_mm);",
            "    color([0.90, 0.15, 0.15, 0.85]) {",
            "        beam_y(front_axle_x, -front_track_mm / 2, 0, front_track_mm);",
            "        beam_y(rear_axle_x, -rear_track_mm / 2, 0, rear_track_mm);",
            "    }",
            "}",
            "",
            "envelope_cage();",
            "datum_cage();",
            "",
        ]
    )
    return "\n".join(lines)


def manifest(dimensions: dict[str, float], evidence: dict[str, dict[str, Any]], scad_path: Path) -> dict[str, Any]:
    return {
        "$comment": "Jumeau 3D initial : enveloppe et reperes, pas carrosserie reconstruite.",
        "schema_version": "1.0.0",
        "twin_id": "TWIN-993-REFERENCE-ENVELOPE-001",
        "status": "reference_envelope",
        "variant": "USA",
        "units": "mm",
        "coordinate_system": {
            "origin": "projection du point avant de l'enveloppe au sol, sur l'axe median",
            "x": "avant vers arriere",
            "y": "gauche/droite autour de l'axe median",
            "z": "vertical depuis le sol",
        },
        "source": {
            "source_id": "SRC-PORSCHE-WORKSHOP-MANUAL-993",
            "measurement_record": "catalog/measurements/MEAS-MANUAL-993-ALL.json",
            "geometry_source": "documented_specification",
        },
        "parameters": {
            name: {
                "value_mm": dimensions[name],
                "source_measurement_id": evidence[name]["value_id"],
                "pdf_page": evidence[name]["pdf_page"],
                "value_text": evidence[name]["value_text"],
                "extraction_status": evidence[name]["extraction_status"],
            }
            for name in PARAMETERS
        },
        "geometry": {
            "master_format": "OpenSCAD",
            "master_file": str(scad_path.relative_to(ROOT)),
            "accuracy_mm": None,
            "derived_files": [],
        },
        "assumptions": [
            "La cage est une enveloppe de reference et ne represente pas les surfaces de carrosserie.",
            "Les positions des essieux sont centrees dans la longueur uniquement pour visualiser l'empattement.",
            "Aucun rayon, pneu, porte-a-faux, interface ou volume interieur n'est deduit.",
        ],
        "validation": {
            "status": "reference_only",
            "vehicle_tested": False,
            "fitment_claim": False,
            "engineering_use": False,
        },
    }


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--measurements", type=Path, default=MEASUREMENTS)
    parser.add_argument("--scad", type=Path, default=DEFAULT_SCAD)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args(arguments)

    dimensions, evidence = collect(load_values(args.measurements))
    args.scad.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.scad.write_text(scad(dimensions, evidence), encoding="utf-8")
    args.manifest.write_text(
        json.dumps(manifest(dimensions, evidence, args.scad), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {args.scad}")
    print(f"wrote {args.manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
