#!/usr/bin/env python3
"""Render the README parts table from the catalogue records.

The front page used to announce 31 records without naming a single one: you had
to open `catalog/parts/` to learn what the repository contains. A hand-written
table would drift with the next record, so this one is generated.

    python3 scripts/render_parts_table.py --write   # rewrite the README block
    python3 scripts/render_parts_table.py --check   # fail if it has drifted

`--check` runs in `make check`: the table cannot misstate a part's status for
longer than one commit.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FICHES = ROOT / "catalog" / "parts"
README = ROOT / "README.md"

DEBUT = "<!-- parts:start - generated by scripts/render_parts_table.py -->"
FIN = "<!-- parts:end -->"

# Reading order, not alphabetical: from the engine down to the accessories,
# because that is where the repository has put its work.
SYSTEMES = [
    ("ENG", "Engine, intake and cooling"),
    ("TURBOCHARGER", "Turbocharger"),
    ("EXH", "Exhaust"),
    ("BODY", "Body"),
    ("INT", "Interior"),
    ("ELEC", "Lighting"),
    ("WHL", "Wheels"),
]

STATUTS = {
    "prohibited_pending_engineering": "**prohibited pending engineering**",
    "safety_critical": "**safety-critical**",
    "functional": "functional",
    "non_critical": "non-critical",
}

PROCEDES = {"undecided": "undecided"}

# Four records keep a French `name` because pinned supplier RFQ files under
# evidence/ embed it verbatim (see docs/TRANSLATION.md). Pages show an English
# display name instead; the record itself is not touched.
NOMS_AFFICHES = {
    "993-ELEC-HEADLAMP-SPRING-HOOK-F0-0001": "Headlamp spring hook repair, F0 aluminum concept",
    "993-EXH-OVAL-TIP-TI-F1-0001": "Oval exhaust tip, F1 titanium variant",
    "993-INT-DOOR-OPENER-LEVER-F0-0001": "993 interior door opener lever, F0 aluminum concept",
    "993-INT-SWITCH-TRIM-RING-F1-0001": "Aluminum switch trim ring, F1 reconstruction",
}


def nom(fiche: dict) -> str:
    return NOMS_AFFICHES.get(fiche["part_id"], fiche["name"])


# The validation ladder of catalog/schemas/part.schema.json, in order.
ECHELLE = ["concept", "dimensionally_reviewed", "prototype_fitted",
           "functionally_tested", "engineering_reviewed", "released"]

# Pie slices in a fixed order, so the chart does not reshuffle between records.
ORDRE_STATUTS = ["prohibited_pending_engineering", "safety_critical",
                 "functional", "non_critical"]


def grille(fiches: list, par_ligne: int = 6) -> list[str]:
    """Thumbnail grid of every part with a CAD view; each tile opens the part's folder."""
    tuiles = []
    for _, d in fiches:
        dossier = f"parts/{d['part_id'].lower()}"
        if (ROOT / dossier / "media" / "preview.png").exists():
            libelle = court(nom(d).split(",")[0], 34)
            pj = ROOT / dossier / "print" / "print.json"
            if pj.exists():
                libelle = ("🧩 " if json.loads(pj.read_text(encoding="utf-8")).get("kind") == "mockup"
                           else "🖨️ ") + libelle
            tuiles.append(f'<td align="center" width="16%"><a href="{dossier}/">'
                          f'<img src="{dossier}/media/preview.png" alt="{libelle}" width="130"><br>'
                          f"<sub>{libelle}</sub></a></td>")
    if not tuiles:
        return []
    niveaux = {d.get("validation", {}).get("status") for _, d in fiches}
    mesurees = sum(1 for _, d in fiches if d.get("geometry", {}).get("source_type") in ("measured", "scan"))
    etat = (f"{len(fiches)} of {len(fiches)} records are at `concept`" if niveaux == {"concept"}
            else "see each record's validation status")
    etat += f", and {mesurees} of {len(fiches)} have measured geometry"
    def genre(d):
        f = ROOT / "parts" / d["part_id"].lower() / "print" / "print.json"
        return json.loads(f.read_text(encoding="utf-8")).get("kind") if f.exists() else None
    prets = [nom(d).split(",")[0] for _, d in fiches if genre(d) == "part_print"]
    maquettes = [nom(d).split(",")[0] for _, d in fiches if genre(d) == "mockup"]
    imprimables = " ".join(filter(None, [
        f"🖨️ Printable as designed, fit unchecked: {', '.join(prets)}." if prets else "",
        f"🧩 Printable as an engraved display mock-up, never for use: {', '.join(maquettes)}." if maquettes else "",
    ])) or "None is a print file."
    out = ["> [!CAUTION]",
           "> These are concept models for studying parts in software, not validated parts."
           + (" 🖨️ marks a printable design, 🧩 an engraved display mock-up (never for use)." if any(
               (ROOT / "parts" / d["part_id"].lower() / "print" / "print.json").exists() for _, d in fiches)
              else " None is ready to print."),
           "", "<table>"]
    for i in range(0, len(tuiles), par_ligne):
        out += ["<tr>"] + tuiles[i:i + par_ligne] + ["</tr>"]
    out += ["</table>", "",
            "*Concept CAD blocks rendered from each part's own CAD by "
            "`scripts/render_part_previews.py`. **None of these is the original part, and none "
            f"is validated**: {etat}. {imprimables} Click a part to see it next to the original.*", ""]
    return out


def graphiques(fiches: list) -> list[str]:
    """Two Mermaid charts computed from the records: never typed by hand."""
    classes = [d["classification"]["safety_class"] for _, d in fiches]
    niveaux = [d.get("validation", {}).get("status", "concept") for _, d in fiches]
    out = ["```mermaid", f"pie showData title {len(fiches)} part records by safety class"]
    for cle in ORDRE_STATUTS:
        if classes.count(cle):
            libelle = STATUTS[cle].strip("*")
            out.append(f'    "{libelle}" : {classes.count(cle)}')
    out += ["```", "", "```mermaid", "flowchart LR"]
    for i, niveau in enumerate(ECHELLE):
        out.append(f'    L{i}["{niveau}<br/><b>{niveaux.count(niveau)}</b> records"]')
    out.append("    " + " --> ".join(f"L{i}" for i in range(len(ECHELLE))))
    out += ["    classDef here fill:#fff4d6,stroke:#b7791f,color:#1a1a1a;",
            "    classDef empty fill:#f4f4f4,stroke:#9e9e9e,color:#6b6b6b;"]
    for i, niveau in enumerate(ECHELLE):
        out.append(f"    class L{i} {'here' if niveaux.count(niveau) else 'empty'}")
    out += ["```", "",
            "*The validation ladder of `catalog/schemas/part.schema.json`, with the number "
            "of records whose `validation.status` names each step. Both charts are computed "
            "from the records.*", ""]
    return out


def court(texte: str, limite: int) -> str:
    """Cut without lying: a visible truncation beats a paraphrase."""
    texte = texte.strip()
    return texte if len(texte) <= limite else texte[: limite - 1].rstrip(" ,;") + "…"


def matiere(fiche: dict) -> str:
    m = fiche["manufacturing"]["material"]
    valeur = m.get("grade") or m.get("family") or "undetermined"
    # The first semicolon separates the grade from its caveats; the "status"
    # column already says that nothing is qualified.
    return court(valeur.split(";")[0], 40)


def lignes() -> list[str]:
    fiches = []
    for chemin in sorted(FICHES.glob("*.json")):
        d = json.loads(chemin.read_text(encoding="utf-8"))
        fiches.append((chemin, d))

    connus = {cle for cle, _ in SYSTEMES}
    inconnus = sorted({d["part_id"].split("-")[1] for _, d in fiches} - connus)
    if inconnus:
        raise SystemExit(
            f"system(s) without a heading in SYSTEMES: {', '.join(inconnus)}"
        )

    out = [DEBUT, ""] + grille(fiches) + graphiques(fiches)
    for cle, intitule in SYSTEMES:
        groupe = [(c, d) for c, d in fiches if d["part_id"].split("-")[1] == cle]
        if not groupe:
            continue
        out += [f"**{intitule}**", "",
                "| part | candidate material | process | status |",
                "|---|---|---|---|"]
        for chemin, d in groupe:
            libelle = court(nom(d).split(",")[0], 46)
            # The link opens the description page, not the JSON record: the page
            # cites the record, its sources, its evidence and its images.
            rel = f"docs/pieces/{d['part_id'].lower()}.md"
            proc = d["manufacturing"]["preferred_process"]
            out.append(f"| [{libelle}]({rel}) | {matiere(d)} | "
                       f"{PROCEDES.get(proc, proc)} | "
                       f"{STATUTS[d['classification']['safety_class']]} |")
        out.append("")

    compte = len(fiches)
    interdites = sum(
        1 for _, d in fiches
        if d["classification"]["safety_class"] == "prohibited_pending_engineering"
    )
    out += [f"*{compte} records, {interdites} of them prohibited pending "
            "engineering, none released. Each link opens the part's description "
            "page in [`docs/pieces/`](docs/pieces/), generated from its "
            "`catalog/parts/*.json` record; the design dossiers are in "
            "[`docs/993/`](docs/993/). Table generated by "
            "`scripts/render_parts_table.py`, checked by `make check`.*",
            "", FIN]
    return out


def bloc() -> str:
    return "\n".join(lignes())


def remplace(texte: str, neuf: str) -> str:
    if DEBUT not in texte or FIN not in texte:
        raise SystemExit(f"markers {DEBUT} / {FIN} missing from README.md")
    avant = texte.split(DEBUT)[0]
    apres = texte.split(FIN, 1)[1]
    return avant + neuf + apres


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()

    texte = README.read_text(encoding="utf-8")
    attendu = remplace(texte, bloc())

    if a.write:
        if attendu != texte:
            README.write_text(attendu, encoding="utf-8")
            print("README.md  parts table rewritten")
        else:
            print("README.md  parts table already up to date")
        return 0

    if attendu != texte:
        print("FAIL   the README parts table no longer matches the records "
              "in catalog/parts/.\n"
              "       rerun: python3 scripts/render_parts_table.py --write",
              file=sys.stderr)
        return 1
    print("OK   README.md, parts table matches the catalogue records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
