#!/usr/bin/env python3
"""Render one description page per part, from its catalogue record.

The README table used to link to `catalog/parts/*.json`: readable by a tool, not
by a person. Each part now has its page in `docs/pieces/`, generated from the
same record, with its sources, its evidence and its images.

    python3 scripts/render_part_pages.py --write   # (re)write the pages
    python3 scripts/render_part_pages.py --check   # fail if a page has drifted

`--check` runs in `make check`: a page cannot contradict its record for longer
than one commit. Nothing is summarized or reworded: values are copied, and a
missing field is written as missing.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from render_parts_table import ECHELLE, PROCEDES, STATUTS, nom  # noqa: E402

FICHES = ROOT / "catalog" / "parts"
PAGES = ROOT / "docs" / "pieces"
DOSSIERS = ROOT / "docs" / "993"
ENTETE = "<!-- generated by scripts/render_part_pages.py - do not edit by hand -->"


def lien(cible: Path, depuis: Path) -> str:
    """Relative path from the page to a repository target (pages live in docs/pieces/)."""
    remontee = [".."] * len(depuis.relative_to(ROOT).parts[:-1])
    return Path(*remontee).joinpath(cible.relative_to(ROOT)).as_posix()


def valeur(x) -> str:
    if x is None or x == [] or x == {}:
        return "not recorded"
    if isinstance(x, bool):
        return "yes" if x else "no"
    if isinstance(x, list):
        return ", ".join(valeur(v) for v in x)
    if isinstance(x, dict):
        return " ; ".join(f"{k}: {valeur(v)}" for k, v in x.items())
    return str(x)


def tableau(page: Path, paires) -> list[str]:
    out = ["| field | value |", "|---|---|"]
    for cle, brut in paires:
        texte = valeur(brut).replace("|", "\\|").replace("\n", " ")
        out.append(f"| {cle} | {texte} |")
    return out + [""]


def fichiers(page: Path, chemins, titre: str) -> list[str]:
    out = [f"**{titre}**", ""]
    if not chemins:
        return out + ["- none", ""]
    for rel in chemins:
        cible = ROOT / rel
        etat = "" if cible.exists() else " — *missing from the repository*"
        out.append(f"- [`{rel}`]({lien(cible, page)}){etat}" if cible.exists() else f"- `{rel}`{etat}")
    return out + [""]


def images(part_id: str, page: Path) -> list[str]:
    dossier = ROOT / "parts" / part_id.lower()
    trouvees = sorted(dossier.rglob("*.png")) if dossier.is_dir() else []
    if not trouvees:
        return []
    out = ["## Images", ""]
    for img in trouvees[:6]:
        rel = img.relative_to(ROOT).as_posix()
        legende = (" — concept CAD block, **not** the original part, not a print file"
                   if "media" in img.relative_to(ROOT).parts else " — a screening output, not a validation")
        out += [f"![{img.stem}]({lien(img, page)})", "", f"*`{rel}`{legende}.*", ""]
    return out


def dossiers_lies(part_id: str, page: Path) -> list[str]:
    if not DOSSIERS.is_dir():
        return []
    lies = [p for p in sorted(DOSSIERS.glob("*.md"))
            if part_id.lower() in p.read_text(encoding="utf-8", errors="replace").lower()]
    if not lies:
        return []
    return ["## Design dossiers", ""] + \
        [f"- [{p.stem}]({lien(p, page)})" for p in lies] + [""]


def echelle(niveau: str, classe: str | None) -> list[str]:
    """The part's position on the validation ladder, as a Mermaid flowchart."""
    rang = ECHELLE.index(niveau) if niveau in ECHELLE else -1
    out = ["```mermaid", "flowchart LR"]
    for i, etape in enumerate(ECHELLE):
        out.append(f'    L{i}["{etape}"]')
    out.append("    " + " --> ".join(f"L{i}" for i in range(len(ECHELLE))))
    if classe == "prohibited_pending_engineering" and rang >= 0 and rang + 1 < len(ECHELLE):
        out += ['    X["⛔ prohibited pending engineering"]',
                f"    L{rang} -. blocked .-> X"]
    out += ["    classDef here fill:#fff4d6,stroke:#b7791f,color:#1a1a1a,stroke-width:3px;",
            "    classDef done fill:#e3f1e6,stroke:#2e7d32,color:#1a1a1a;",
            "    classDef todo fill:#f4f4f4,stroke:#9e9e9e,color:#6b6b6b;",
            "    classDef stop fill:#fde2e1,stroke:#c0392b,color:#1a1a1a;"]
    for i in range(len(ECHELLE)):
        etat = "here" if i == rang else ("done" if i < rang else "todo")
        out.append(f"    class L{i} {etat}")
    if any(l.startswith("    X[") for l in out):
        out.append("    class X stop")
    return out + ["```", "",
                  f"*Validation ladder of `catalog/schemas/part.schema.json`; this record is at "
                  f"`{niveau}`.*", ""]


def page_markdown(fiche: dict, chemin_fiche: Path) -> str:
    part_id = fiche["part_id"]
    page = PAGES / f"{part_id.lower()}.md"
    if part_id == "993-ENG-CARRIER-0001":
        return presentation_carrier(fiche, chemin_fiche, page)
    classification = fiche.get("classification", {})
    fabrication = fiche.get("manufacturing", {})
    matiere = fabrication.get("material", {})
    geometrie = fiche.get("geometry", {})
    provenance = fiche.get("provenance", {})
    titane = fiche.get("titanium", {})
    validation = fiche.get("validation", {})
    statut = STATUTS.get(classification.get("safety_class"), classification.get("safety_class", "unknown"))
    procede = fabrication.get("preferred_process", "unknown")

    out = [ENTETE, "", f"# {nom(fiche)}", "",
           f"**Status: {statut}. No part is released; see [SAFETY.md]({lien(ROOT / 'SAFETY.md', page)}).**", "",
           fiche.get("description", "").strip(), ""]
    out += echelle(validation.get("status", "concept"), classification.get("safety_class"))
    out += [f"Catalogue record: [`{chemin_fiche.relative_to(ROOT).as_posix()}`]({lien(chemin_fiche, page)})", ""]

    out += ["## Identity", ""]
    vehicule = fiche.get("vehicle", {})
    annees = vehicule.get("model_years", {})
    out += tableau(page, [
        ("identifier", part_id),
        ("generation", vehicule.get("generation")),
        ("variants", vehicule.get("variants")),
        ("model years", f"{annees.get('from')} to {annees.get('to')}" if annees else None),
        ("Porsche part numbers", vehicule.get("porsche_part_numbers")),
        ("category", classification.get("category")),
        ("safety class", classification.get("safety_class")),
        ("intended use", classification.get("intended_use")),
    ])

    out += ["## Material and manufacturing", ""]
    out += tableau(page, [
        ("preferred process", PROCEDES.get(procede, procede)),
        ("candidate processes", fabrication.get("candidate_processes")),
        ("material family", matiere.get("family")),
        ("grade", matiere.get("grade")),
        ("standard", matiere.get("standard")),
        ("supplier requirements", fabrication.get("supplier_requirements")),
        ("post-processing", fabrication.get("post_processing")),
    ])
    if titane.get("applicable"):
        out += ["**Titanium**", ""]
        out += tableau(page, [
            ("alloy", titane.get("alloy")),
            ("heat treatment", titane.get("heat_treatment")),
            ("HIP", titane.get("hip_required")),
            ("machined surfaces", titane.get("machined_surfaces")),
            ("inspection", titane.get("inspection")),
            ("galvanic isolation", titane.get("galvanic_isolation")),
            ("fatigue assumptions", titane.get("fatigue_assumptions")),
        ])

    out += ["## Geometry", ""]
    out += tableau(page, [
        ("source type", geometrie.get("source_type")),
        ("master format", geometrie.get("master_format")),
        ("units", geometrie.get("units")),
        ("accuracy (mm)", geometrie.get("accuracy_mm")),
    ])
    maitre = geometrie.get("master_file")
    out += fichiers(page, [maitre] if maitre else [], "Master file")
    out += fichiers(page, geometrie.get("derived_files") or [], "Derived files")

    out += images(part_id, page)

    out += ["## Provenance and sources", ""]
    out += tableau(page, [("record license", provenance.get("record_license"))])
    sources = provenance.get("sources") or []
    if sources:
        out += ["**Sources**", ""]
        for s in sources:
            titre = s.get("title") or s.get("id") or "source"
            url = s.get("url")
            note = s.get("note") or s.get("access") or ""
            ligne = f"- [{titre}]({url})" if url else f"- {titre}"
            out.append(f"{ligne}{' — ' + str(note) if note else ''}")
        out.append("")

    out += ["## Validation", ""]
    out += tableau(page, [
        ("status", validation.get("status")),
        ("vehicle tested", validation.get("vehicle_tested")),
        ("reviewed by", validation.get("reviewed_by")),
        ("limitations", validation.get("limitations") or validation.get("notes")),
    ])
    out += fichiers(page, validation.get("evidence") or [], "Evidence")

    out += dossiers_lies(part_id, page)

    out += ["---", "",
            "*Page generated from the catalogue record by `scripts/render_part_pages.py`, "
            "checked by `make check`. Corrections go in the record, not here.*", ""]
    return "\n".join(out)


PARTS = ROOT / "parts"
TWINS = ROOT / "catalog" / "twins"

# Callout per safety class, with SAFETY.md's own definition and publication rule.
ALERTES = {
    "prohibited_pending_engineering": ("CAUTION", "**Prohibited pending engineering** — risk, or "
                                       "insufficient data. Never published as a released part."),
    "safety_critical": ("WARNING", "**Safety-critical** — failure could cause loss of control, fire or "
                        "injury. Published only after formal engineering review."),
    "functional": ("NOTE", "**Functional** — loaded part whose failure can immobilize or damage the "
                   "vehicle. Published only after documented functional testing."),
    "non_critical": ("NOTE", "**Non-critical** — trim, or a part whose failure creates no immediate "
                     "hazard. Published only after dimensional and fit validation."),
}

DOSSIERS_ROLE = {
    "source": "parametric source — the editable master that generates the geometry",
    "derived": "CAD exports generated from the source (STEP for CAD tools, STL for meshing)",
    "evidence": "screens, reports and manifests — **pinned by SHA-256, never edited by hand**",
    "print": "**ready-to-print files**: 3MF project, STL and instructions",
    "media": "concept-model views rendered from the CAD by `scripts/render_part_previews.py` — not pictures of the original",
}


# Sources that describe a material or a process, not the original part itself.
EXCLUS_ORIGINAL = ("data sheet", "datasheet", "pds-", "/data-sheets/", "material data",
                   "astm", "iso ", "standard", "process parameter", "eos.info",
                   "product sheet", "product_sheet")


def lisible(x) -> str:
    """A snake_case placeholder is shown as code, not as if it were prose."""
    texte = valeur(x)
    parts = [f"`{p}`" if "_" in p and " " not in p.strip() else p for p in texte.split(", ")]
    return ", ".join(parts)


def badge(label: str, value: str, color: str) -> str:
    esc = lambda s: str(s).replace("-", "--").replace("_", "__").replace(" ", "%20")
    return f"![{label}: {value}](https://img.shields.io/badge/{esc(label)}-{esc(value)}-{color})"


def fichiers_du_dossier(dossier: Path) -> list[Path]:
    """Tracked or addable files of a part folder: what a clone of the repository shows."""
    import subprocess
    sortie = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "--", str(dossier)],
        cwd=ROOT, capture_output=True, text=True, check=True).stdout.split("\n")
    return sorted(ROOT / f for f in sortie if f and not f.endswith("/README.md") and (ROOT / f).exists())


def jumeaux_lies(part_id: str) -> list[Path]:
    return [p for p in sorted(TWINS.glob("*.json")) if part_id in p.read_text(encoding="utf-8")]


IMPELLER_ID = "993-ENG-COOLING-IMPELLER-ALSI10MG-F0-0001"


def presentation_impeller(fiche: dict, chemin_fiche: Path) -> str:
    """Custom English presentation of the archived Carrera F0 impeller.

    The generic wheel view and the orthographic blocks of the archived concept
    were removed from the page on 2026-09-29: they showed a synthetic Carrera
    study block that read as a Turbo part. The page now presents the current
    M64/60 Turbo fan programme with its editable sources, its real PicoGK
    visuals, the fan-drive metrology, and the provenance limits — and keeps
    the archived concept visibly archived. Regenerate the removed views with
    `make part-previews` if ever needed again.
    """
    part_id = fiche["part_id"]
    page = PARTS / part_id.lower() / "README.md"
    classification = fiche.get("classification", {})
    classe = classification.get("safety_class", "unknown")
    procede = fiche.get("manufacturing", {}).get("preferred_process", "undecided")
    niveau = fiche.get("validation", {}).get("status", "concept")
    vehicule = fiche.get("vehicle", {})
    annees = vehicule.get("model_years", {})
    reprise = lien(ROOT / "twins" / "993-engine-cooling-fan-system-f0", page)
    rel_page = f"docs/pieces/{part_id.lower()}.md"

    def L(p: str) -> str:
        return lien(ROOT / p, page)

    badges = " ".join([
        badge("status", f"{niveau}, not a print file", "critical"),
        badge("safety", STATUTS.get(classe, classe).strip("*"), "critical"),
        badge("candidate process", PROCEDES.get(procede, procede), "lightgrey"),
    ])
    out = [ENTETE, "", '<div align="center">', "", f"# {nom(fiche)}", "",
           f"**`{part_id}`** · Porsche {vehicule.get('generation', '?')}"
           + (f" · {annees.get('from')}–{annees.get('to')}" if annees else ""), "",
           badges, "", "</div>", ""]

    out += [f"""> [!CAUTION]
> **Not ready to print, and not a copy of the original part.** This folder preserves an archived Carrera F0 concept. The current Turbo study is linked below. No part is declared dimensionally accurate, fitted, tested, safe or released without supporting evidence: see [SAFETY.md]({L('SAFETY.md')}).

## Current programme: M64/60 Turbo cooling fan

Target: **993 Turbo M64.60 with the PMB / Classic Retrofit 240 A alternator**. Porsche PET illustration 105-00, plates 77–78, distinguishes the Turbo rotor (964 106 015 22) from the Carrera rotor (964 106 015 31, this folder's catalogue record). The experimental rotor remains partly hypothetical.

**Latest campaign:** [blade/clearance mesh recovery and CFD evidence]({reprise}/MESH_RECOVERY_20261002.md), following the [local Qwen → PicoGK → OpenFOAM / CalculiX → OpenUSD run]({reprise}/QWEN_CHAIN_20261002.md). The recovery report carries the current calculation status and archived evidence. The isolated-duct calculations do not establish airflow delivered to the installed engine.

| Work | Editable sources and evidence | Status |
| --- | --- | --- |
| Reference rebuild: 11 blades, ventilated cup, 12 windows | [Rebuild report]({reprise}/REFERENCE_REBUILD.md), [parameters]({reprise}/source/picogk-reference/reference.json), [PicoGK C#]({reprise}/source/picogk-reference/Program.cs) | Visual reference reconstruction; unmeasured parameters explicitly identified |
| Organic blade candidates A–E | [Study]({reprise}/ORGANIC_BLADE_STUDY.md), [candidate E parameters]({reprise}/source/picogk-reference/organic-e.json) | Documented numerical attempts, including failures; no validated aerodynamic optimum |
| Parametric rotor and housing, wave 2 | [M64Fan.cs]({L('parts/m64-cooling-fan-0001/geometry/M64Fan.cs')}), [configuration]({L('parts/m64-cooling-fan-0001/geometry/fan-config.json')}) | Editable, labelled assumptions; no archived compiled output for this separate source |
| Earlier actuator-disc CFD, OpenFOAM v2312 | [Baseline rig]({L('simulation/993-fan-baseline/README.md')}) | Exploratory surrogate; not an installed performance prediction |
| Fan-drive metrology, M64-ACQ-0005 | [Dimensions]({L('twins/m64-engine-system/metrology/fan-drive/fan-drive-dimensions.json')}), [scan record]({L('catalog/scans/scan-fan-drive-0p21mm.json')}) | Initial scan analysis; ±4 mm uncertainty and unresolved discrepancies |
| Metal printing release | [Release dossier]({reprise}/PRINT_RELEASE.md) | **HOLD — no printing authorization** |

### Views generated from the actual study geometry

![Reconstructed rotor: front, rear, section and exploded views]({reprise}/results/reference/reference-review.png)

*Actual PicoGK mesh regenerated by `source/build_reference_review.py` from the [editable parameters]({reprise}/source/picogk-reference/reference.json). Status: `visual_reference_reconstruction`; [generation record]({reprise}/results/reference/generation.json). This is hypothetical CAD, not a photograph of a manufactured part.*

![Organic candidate E: actual PicoGK mesh views]({reprise}/results/organic/e/review/reference-review.png)

*Candidate E: [mesh checks]({reprise}/results/organic/e/review/validation.json). Design hypothesis; no validated airflow gain or verified mating interfaces.*

### Fan-drive metrology

The initial M64-ACQ-0005 analysis used 1,256,836 scan vertices, nominal scan precision 0.21 mm and assumed millimetre units. Results from [fan_drive_metrology.py]({L('twins/m64-engine-system/metrology/fan-drive/fan_drive_metrology.py')}):

| Dimension | Estimate | Uncertainty | Limitation |
| --- | ---: | ---: | --- |
| Fan pulley diameter | 229.5 mm | ±4 mm | Unresolved difference from the earlier ~255.6 mm estimate |
| Gear flange diameter | 214.2 mm | ±4 mm | Outer disc band |
| Tooth-tip diameter | 104.0 mm | ±4 mm | Radius-truncated analysis; earlier estimate was 127.6 mm |

These are preliminary estimates, not exact dimensions. The single-pass harmonic analysis was truncated at a 140 mm radius and lacks traceable instrument metrology.

## Provenance and limits

- The 11 blades and 12 windows were counted from FVD photographs, not a dimensioned drawing.
- Nominal 245 mm rotor diameter is an interpretation of commercial data, without an OEM tolerance.
- Cup depth, blade pitch, chords, thicknesses and radii remain labelled modelling assumptions.
- Hub, bearing, housing, rear cone and PMB mating interfaces are not dimensionally verified.
- The CFD lacks a measured engine resistance curve and a validated installed assembly. Rendering or solver success does not establish engine cooling performance.
- Printing remains on hold; no material/process is qualified for the rotating blades.
- Results from the archived Carrera F0 concept do not transfer to the rebuilt rotor.

## Measurements still needed

1. Confirm the actual Turbo hub and bearing interface before defining fits.
2. Measure the housing and radial rotor clearance.
3. Measure the selected PMB / Classic Retrofit 240 A interfaces and rear cone.
4. Reanalyse or scan the complete drive without radius truncation, with instrument traceability.
5. Measure the blade pitch on an original Turbo rotor.

## Archived Carrera F0 concept

This folder retains the [build123d source]({L('parts/993-eng-cooling-impeller-alsi10mg-f0-0001/source/cooling_impeller.py')}), [STEP]({L('parts/993-eng-cooling-impeller-alsi10mg-f0-0001/derived/cooling_impeller_alsi10mg_f0.step')}), [STL]({L('parts/993-eng-cooling-impeller-alsi10mg-f0-0001/derived/cooling_impeller_alsi10mg_f0.stl')}) and [engineering screen]({L('parts/993-eng-cooling-impeller-alsi10mg-f0-0001/evidence/engineering-screen.json')}). Evidence is SHA-256 pinned. The concept failed integration with its F0 housing: −14 mm radial clearance. Its 280 mm diameter, hub and twelve blades are synthetic study geometry, not a Turbo part.

The generic wheel and schematic orthographic images were removed from this presentation on 29 September 2026 because they could be mistaken for the Turbo design. They remain reproducible from the archived STEP with `make part-previews`.

## Related records

- [Full catalogue description]({lien(PAGES / f'{part_id.lower()}.md', page)}) (`{rel_page}`)
- [Catalogue source of truth]({lien(chemin_fiche, page)}) (`{chemin_fiche.relative_to(ROOT).as_posix()}`)
- [F0 design dossier]({L('docs/993/993_COOLING_IMPELLER_ALSI10MG_F0.md')})
- [System dossier]({L('docs/993/993_ENGINE_COOLING_FAN_SYSTEM_F0.md')})
- [PorscheFanatics project presentation](https://porschefanatics.com/projects/993-turbo-fan/)
- [Digital twin record]({L('catalog/twins/twin-993-engine-cooling-fan-system-f0.json')})
- [Safety rules]({L('SAFETY.md')})

---

*Generated by `scripts/render_part_pages.py` and checked by `make check`. Update the catalogue record or this part's presentation template, not the generated page.*
"""]
    return "\n".join(out)


def presentation_carrier(fiche: dict, chemin_fiche: Path, page: Path) -> str:
    """Present the current study separately from the retained catalogue master."""
    manifest_path = ROOT / "parts/993-eng-carrier-0001/media/r9/study-public.json"
    study = json.loads(manifest_path.read_text(encoding="utf-8"))
    for asset in study["assets"]:
        path = (ROOT / asset["path"]).resolve()
        path.relative_to(ROOT)
        if hashlib.sha256(path.read_bytes()).hexdigest() != asset["sha256"]:
            raise ValueError(f"Carrier study asset has drifted: {asset['path']}")
    template = (ROOT / "scripts/templates/carrier-study.md.in").read_text(encoding="utf-8")
    for field, group in (("study_images", "geometry"), ("mechanical_images", "mechanical")):
        template = template.replace("{{" + field + "}}", "\n\n".join(
            f"![{asset['caption']}]({lien(ROOT / asset['path'], page)})\n\n*{asset['caption']}*"
            for asset in study["assets"] if asset.get("display") and asset.get("group") == group))
    template = template.replace("{{study_provenance}}",
        f"[Public study manifest]({lien(manifest_path, page)}) records the revision, "
        "artifact SHA-256 digests, representation provenance and publication limits. "
        + study["provenance_note"])
    template = template.replace("{{mass_rows}}", "\n".join(
        f"| {row['representation']} | {row['mass_kg']:.9f} kg | {row['meaning']} |"
        for row in study["masses"]))
    template = template.replace("{{stress_rows}}", "\n".join(
        f"| {row['site']} | {row['h_over_2_mpa']:,.1f} MPa | {row['h_over_4_mpa']:,.1f} MPa |"
        for row in study["mechanical_screen"]["sites"]))
    values = {
        "density": f"{study['material_candidate']['density_kg_m3']:,.0f}",
        "ribs": str(study["nominal_sections_mm"]["ribs"]),
        "center": str(study["nominal_sections_mm"]["center"]),
        "force": f"{study['mechanical_screen']['hypothetical_force_n']:,}",
        "torque": str(study["mechanical_screen"]["hypothetical_torque_nm"]),
    }
    for key, value in values.items():
        template = template.replace("{{" + key + "}}", value)
    template = re.sub(r"\{\{repo:([^}]+)\}\}",
                      lambda match: lien(ROOT / match.group(1), page), template)
    template = template.replace("{{name}}", nom(fiche))
    template = template.replace("{{status}}", fiche["validation"]["status"])
    template = template.replace("{{record}}", lien(chemin_fiche, page))
    if "{{" in template:
        raise ValueError("Unresolved carrier presentation template field")
    return ENTETE + "\n\n" + template


def presentation(fiche: dict, chemin_fiche: Path) -> str:
    """The README GitHub shows when a part folder is opened: the concept next to the original."""
    part_id = fiche["part_id"]
    if part_id == "993-ENG-CARRIER-0001":
        return presentation_carrier(fiche, chemin_fiche, PARTS / part_id.lower() / "README.md")
    if part_id == IMPELLER_ID:
        return presentation_impeller(fiche, chemin_fiche)
    dossier = PARTS / part_id.lower()
    page = dossier / "README.md"
    classification = fiche.get("classification", {})
    classe = classification.get("safety_class", "unknown")
    fabrication = fiche.get("manufacturing", {})
    matiere = fabrication.get("material", {})
    validation = fiche.get("validation", {})
    niveau = validation.get("status", "concept")
    vehicule = fiche.get("vehicle", {})
    annees = vehicule.get("model_years", {})
    procede = fabrication.get("preferred_process", "undecided")
    geometrie = fiche.get("geometry", {})

    apercu = dossier / "media" / "preview.png"
    vues = dossier / "media" / "views.png"
    infos = dossier / "media" / "preview.json"
    boite = json.loads(infos.read_text(encoding="utf-8")).get("bounding_box_mm") if infos.exists() else None

    kit_json = dossier / "print" / "kit.json"
    kit = json.loads(kit_json.read_text(encoding="utf-8")) if kit_json.exists() else None
    print_json = dossier / "print" / "print.json"
    impression = json.loads(print_json.read_text(encoding="utf-8")) if print_json.exists() else None
    couleur = {"prohibited_pending_engineering": "critical", "safety_critical": "orange",
               "functional": "yellow", "non_critical": "informational"}.get(classe, "lightgrey")
    out = [ENTETE, "", '<div align="center">', "", f"# {nom(fiche)}", "",
           f"**`{part_id}`** · Porsche {vehicule.get('generation', '?')}"
           + (f" · {annees.get('from')}–{annees.get('to')}" if annees else ""), "",
           " ".join([badge("status", f"{niveau}, display mock-up printable" if (impression or {}).get("kind") == "mockup" else
                           f"{niveau}, printable" if impression else
                           (f"{niveau}, fit-test kit ready" if kit else f"{niveau}, not a print file"),
                           "orange" if (impression or {}).get("kind") == "mockup" else
                           "success" if (kit or impression) else "critical"),
                     badge("safety", STATUTS.get(classe, classe).strip("*"), couleur),
                     badge("candidate process", PROCEDES.get(procede, procede), "lightgrey")]), "",
           "</div>", ""]

    # The first thing a reader sees is what this is NOT, from the record's own fields.
    source_geo = geometrie.get("source_type", "unknown")
    mesure = {"measured": "measured", "scan": "scanned"}.get(source_geo)
    raisons = [f"validation status `{niveau}`: nothing has been checked against a real part"
               if niveau == "concept" else f"validation status `{niveau}`"]
    if not mesure:
        raisons.append(f"geometry `{source_geo}`: its dimensions are "
                       + ("estimated design variables" if source_geo == "estimated"
                          else "partly sourced, partly assumed")
                       + ", not measured on the original part")
    raisons.append(f"safety class `{classe}`")
    maquette = impression if impression and impression.get("kind") == "mockup" else None
    if maquette:
        s = maquette.get("sliced", {})
        out += ["> [!WARNING]",
                "> **A 1:1 display mock-up is printable — never for use.** [`print/`](print/README.md): "
                f"the design, unchanged except for MOCK-UP / NOT FOR USE engraved in it, sliced in {s.get('time', '?')} "
                f"({s.get('filament_cm3', '?')} cm³). The part itself stays prohibited "
                f"([decision 0011]({lien(ROOT / 'docs' / 'decisions' / '0011-printable-display-mockups-of-prohibited-parts.md', page)})).",
                ""]
    elif impression:
        s = impression.get("sliced", {})
        out += ["> [!TIP]",
                "> **This part is ready to print** — [`print/`](print/README.md): the repository's own "
                f"design, unchanged, sliced in {s.get('time', '?')} ({s.get('filament_cm3', '?')} cm³), "
                "with a PrusaSlicer project and settings. Its fit on the car is not checked yet "
                f"([decision 0010]({lien(ROOT / 'docs' / 'decisions' / '0010-print-the-trim-ring-f1-in-polymer.md', page)})).",
                ""]
    if kit:
        tailles = ", ".join(f"{v['insert_mm'][0]} × {v['insert_mm'][1]}" for v in kit["variants"])
        out += ["> [!TIP]",
                "> **A fit-test kit is ready to print** — [`print/`](print/README.md): "
                f"{len(kit['variants'])} sizes on one plate ({tailles} mm), a PrusaSlicer project and "
                "instructions. It is a measurement instrument, not the finished part "
                f"([decision 0009]({lien(ROOT / 'docs' / 'decisions' / '0009-first-fit-test-print-switch-blank.md', page)})).",
                ""]
    out += ["> [!CAUTION]",
            ("> **Prohibited, not validated, and not a copy of the original.** The mock-up is a display "
             "piece; the model shown here is a" if (impression or {}).get("kind") == "mockup" else
             "> **Printable, but not validated, and not a copy of the original.** The model shown "
             "here is a" if impression else
             "> **The part itself is not validated, and not a copy of the original.** The model shown "
             "here is a" if kit else
             "> **Not ready to print, and not a copy of the original part.** The model shown here is a"),
            ("> design whose fit has not been checked against the car:" if impression else
             "> concept block for studying the part in software:"),
            *[f"> - {r};" for r in raisons],
            f"> - no part in this repository is released — read [SAFETY.md]({lien(ROOT / 'SAFETY.md', page)}).",
            ""]

    originaux = [s for s in fiche.get("provenance", {}).get("sources", []) if s.get("url") and
                 not any(k in f"{s.get('title', '')} {s.get('url', '')}".lower() for k in EXCLUS_ORIGINAL)]
    gauche = ["<b>Original part</b><br><br>"]
    if originaux:
        gauche.append("The original part is documented — pictures, catalogue entries or "
                      "published data — on these pages. They are copyrighted, so they are "
                      "linked here, not copied:<br><br>")
        gauche += [f'↗ <a href="{s["url"]}">{s.get("title", s["url"])}</a><br>' for s in originaux[:4]]
    else:
        gauche.append("<i>No public picture of the original part is recorded yet.</i>")
    plaque = dossier / "print" / "plate.png"
    if kit and plaque.exists():
        droite = ["<b>What you can print today</b><br><br>",
                  f'<a href="print/README.md"><img src="print/plate.png" alt="Fit-test kit, three sizes" width="360"></a><br>',
                  "<sub>The fit-test kit: three sizes that bracket the declared opening. A measurement "
                  "instrument — <b>not</b> the finished part, not a copy of the original.</sub>"]
    elif maquette and (dossier / "print" / "mockup.png").exists():
        droite = ["<b>What you can print: a display mock-up</b><br><br>",
                  f'<a href="print/README.md"><img src="print/mockup.png" alt="Engraved display mock-up of {nom(fiche)}" width="360"></a><br>',
                  "<sub>1:1 display mock-up with MOCK-UP / NOT FOR USE engraved in it. <b>Never</b> for an "
                  "engine; not the original part.</sub>"]
    elif impression and apercu.exists():
        droite = ["<b>This repository's design — what prints</b><br><br>",
                  f'<a href="print/README.md"><img src="media/preview.png" alt="Printable design of {nom(fiche)}" width="340"></a><br>',
                  "<sub>The repository's own design, rendered from the file that prints. <b>Not</b> the "
                  "original part; fit on the car not checked.</sub>"]
    else:
        droite = ["<b>This repository's concept model</b><br><br>"]
    if (kit and plaque.exists()) or (impression and apercu.exists()) or \
            (maquette and (dossier / "print" / "mockup.png").exists()):
        pass
    elif apercu.exists():
        taille = f"{boite[0]} × {boite[1]} × {boite[2]} mm" if boite else ""
        droite += [f'<img src="media/preview.png" alt="Concept CAD block for {nom(fiche)}" width="340"><br>',
                   f"<sub>Concept CAD block{', ' + taille if taille else ''} — <b>not</b> the original "
                   "part, not a print file, not evidence of fit.</sub>"]
    else:
        droite.append("<i>No CAD geometry to show.</i>")
    out += ['<table><tr>', '<td width="50%" valign="top">', *gauche, "</td>",
            '<td width="50%" valign="top" align="center">', *droite, "</td>", "</tr></table>", ""]

    type_alerte, texte_alerte = ALERTES.get(classe, ("NOTE", f"Safety class `{classe}`."))
    out += [f"> [!{type_alerte}]", f"> {texte_alerte}", ""]

    out += ["## What it is", "", fiche.get("description", "").strip() or "*No description recorded.*", ""]
    if classification.get("intended_use"):
        out += ["## What it does on the car", "", classification["intended_use"].strip(), ""]

    grade = matiere.get("grade") or matiere.get("family") or "undetermined"
    out += ["## At a glance", "", "| | |", "|---|---|",
            f"| Porsche part numbers | {valeur(vehicule.get('porsche_part_numbers'))} |",
            f"| variants | {lisible(vehicule.get('variants'))} |",
            f"| candidate material | {grade.split(';')[0].strip()} |",
            f"| candidate process | {PROCEDES.get(procede, procede)} |",
            f"| safety class | `{classe}` |",
            f"| validation status | `{niveau}` |",
            f"| geometry | {valeur(geometrie.get('source_type'))}, master {valeur(geometrie.get('master_format'))}"
            + (f", accuracy {geometrie.get('accuracy_mm')} mm" if geometrie.get("accuracy_mm") is not None else "")
            + " |", ""]

    out += ["## Where it stands", ""] + echelle(niveau, classe)

    if vues.exists():
        out += ["## Views", "", "![Front, side and top orthographic views](media/views.png)", "",
                "*Orthographic views of the same concept CAD, with its bounding dimensions — not drawings of the original part.*", ""]

    autres = [f for f in fichiers_du_dossier(dossier)
              if f.suffix.lower() in (".png", ".svg", ".gif") and "media" not in f.relative_to(dossier).parts]
    if autres:
        out += ["## Screens and evidence images", ""]
        for img in autres[:4]:
            rel = img.relative_to(dossier).as_posix()
            out += [f"![{img.stem}]({rel})", "",
                    f"*`{rel}` — a screening output, not a validation.*", ""]

    fichiers = fichiers_du_dossier(dossier)
    if fichiers:
        out += ["## What's in this folder", "", "| folder | what it holds | files |", "|---|---|---|"]
        groupes: dict[str, list[Path]] = {}
        for f in fichiers:
            rel = f.relative_to(dossier)
            groupes.setdefault(rel.parts[0] if len(rel.parts) > 1 else ".", []).append(f)
        for sous in sorted(groupes, key=lambda n: (n == ".", n)):
            role = DOSSIERS_ROLE.get(sous, "files of this part")
            liens = ", ".join(f"[`{f.relative_to(dossier).as_posix()}`]({f.relative_to(dossier).as_posix()})"
                              for f in groupes[sous][:8])
            if len(groupes[sous]) > 8:
                liens += f", … ({len(groupes[sous])} files)"
            out.append(f"| `{sous}/` | {role} | {liens} |" if sous != "." else f"| (here) | {role} | {liens} |")
        out.append("")

    out += ["## Read more", "",
            f"- **Full description page**, with sources and evidence: "
            f"[docs/pieces/{part_id.lower()}.md]({lien(PAGES / f'{part_id.lower()}.md', page)})",
            f"- **Catalogue record** (source of truth): [`{chemin_fiche.relative_to(ROOT).as_posix()}`]"
            f"({lien(chemin_fiche, page)})"]
    for d in [p for p in sorted(DOSSIERS.glob("*.md"))
              if part_id.lower() in p.read_text(encoding="utf-8", errors="replace").lower()]:
        out.append(f"- **Design dossier**: [{d.stem}]({lien(d, page)})")
    for j in jumeaux_lies(part_id):
        out.append(f"- **Digital twin record**: [`{j.name}`]({lien(j, page)}) — "
                   f"see [twins/README.md]({lien(ROOT / 'twins' / 'README.md', page)})")
    out += [f"- **Safety rules**: [SAFETY.md]({lien(ROOT / 'SAFETY.md', page)})", "",
            "---", "",
            "*This page is generated from the catalogue record by `scripts/render_part_pages.py` "
            "and checked by `make check`. Edit the record, not this page.*", ""]
    return "\n".join(out)


def attendues() -> dict[Path, str]:
    """Description pages in docs/pieces/, then one README per part folder."""
    pages = {}
    for c in sorted(FICHES.glob("*.json")):
        fiche = json.loads(c.read_text(encoding="utf-8"))
        pages[PAGES / f"{fiche['part_id'].lower()}.md"] = page_markdown(fiche, c)
    for c in sorted(FICHES.glob("*.json")):
        fiche = json.loads(c.read_text(encoding="utf-8"))
        if (PARTS / fiche["part_id"].lower()).is_dir():
            pages[PARTS / fiche["part_id"].lower() / "README.md"] = presentation(fiche, c)
    return pages


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()

    pages = attendues()
    if a.write:
        PAGES.mkdir(parents=True, exist_ok=True)
        ecrites = 0
        for chemin, texte in pages.items():
            if not chemin.exists() or chemin.read_text(encoding="utf-8") != texte:
                chemin.write_text(texte, encoding="utf-8")
                ecrites += 1
        for orpheline in sorted(PAGES.glob("*.md")):
            if orpheline not in pages:
                orpheline.unlink()
                print(f"orphan page removed: {orpheline.relative_to(ROOT)}")
        n_readme = sum(1 for c in pages if c.name == "README.md")
        print(f"docs/pieces + parts/*/README.md  {len(pages) - n_readme} + {n_readme} pages, {ecrites} rewritten")
        return 0

    manquantes = [c for c in pages if not c.exists()]
    derivees = [c for c, t in pages.items() if c.exists() and c.read_text(encoding="utf-8") != t]
    orphelines = [p for p in sorted(PAGES.glob("*.md")) if p not in pages] if PAGES.is_dir() else []
    if manquantes or derivees or orphelines:
        for chemin in manquantes:
            print(f"FAIL   missing page: {chemin.relative_to(ROOT)}", file=sys.stderr)
        for chemin in derivees:
            print(f"FAIL   page differs from its record: {chemin.relative_to(ROOT)}", file=sys.stderr)
        for chemin in orphelines:
            print(f"FAIL   page without a record: {chemin.relative_to(ROOT)}", file=sys.stderr)
        print("       rerun: python3 scripts/render_part_pages.py --write", file=sys.stderr)
        return 1
    n_readme = sum(1 for c in pages if c.name == "README.md")
    print(f"OK   docs/pieces and parts/*/README.md, {len(pages) - n_readme} + {n_readme} pages match the catalogue records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
