#!/usr/bin/env python3
"""Render one description page per part, from its catalogue record.

The README table used to link to `catalog/parts/*.json`: readable by a tool, not
by a person. Each part now has its page in `docs/pieces/`, generated from the
same record, with its sources, its evidence and its images.

    python3 scripts/render_part_pages.py --write   # (re)write the pages
    python3 scripts/render_part_pages.py --check   # fail if a page has drifted

`--check` runs in `make check`: a page cannot contradict its record for longer
than one commit. Nothing is summarized or reworded: values are copied, and a
missing field is written as missing.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from render_parts_table import ECHELLE, PROCEDES, STATUTS  # noqa: E402

FICHES = ROOT / "catalog" / "parts"
PAGES = ROOT / "docs" / "pieces"
DOSSIERS = ROOT / "docs" / "993"
ENTETE = "<!-- generated by scripts/render_part_pages.py - do not edit by hand -->"


def lien(cible: Path, depuis: Path) -> str:
    """Relative path from the page to a repository target (pages live in docs/pieces/)."""
    remontee = [".."] * len(depuis.relative_to(ROOT).parts[:-1])
    return Path(*remontee).joinpath(cible.relative_to(ROOT)).as_posix()


def valeur(x) -> str:
    if x is None or x == [] or x == {}:
        return "not recorded"
    if isinstance(x, bool):
        return "yes" if x else "no"
    if isinstance(x, list):
        return ", ".join(valeur(v) for v in x)
    if isinstance(x, dict):
        return " ; ".join(f"{k}: {valeur(v)}" for k, v in x.items())
    return str(x)


def tableau(page: Path, paires) -> list[str]:
    out = ["| field | value |", "|---|---|"]
    for cle, brut in paires:
        texte = valeur(brut).replace("|", "\\|").replace("\n", " ")
        out.append(f"| {cle} | {texte} |")
    return out + [""]


def fichiers(page: Path, chemins, titre: str) -> list[str]:
    out = [f"**{titre}**", ""]
    if not chemins:
        return out + ["- none", ""]
    for rel in chemins:
        cible = ROOT / rel
        etat = "" if cible.exists() else " — *missing from the repository*"
        out.append(f"- [`{rel}`]({lien(cible, page)}){etat}" if cible.exists() else f"- `{rel}`{etat}")
    return out + [""]


def images(part_id: str, page: Path) -> list[str]:
    dossier = ROOT / "parts" / part_id.lower()
    trouvees = sorted(dossier.rglob("*.png")) if dossier.is_dir() else []
    if not trouvees:
        return []
    out = ["## Images", ""]
    for img in trouvees[:6]:
        rel = img.relative_to(ROOT).as_posix()
        out += [f"![{img.stem}]({lien(img, page)})", "", f"*{rel}*", ""]
    return out


def dossiers_lies(part_id: str, page: Path) -> list[str]:
    if not DOSSIERS.is_dir():
        return []
    lies = [p for p in sorted(DOSSIERS.glob("*.md"))
            if part_id.lower() in p.read_text(encoding="utf-8", errors="replace").lower()]
    if not lies:
        return []
    return ["## Design dossiers", ""] + \
        [f"- [{p.stem}]({lien(p, page)})" for p in lies] + [""]


def echelle(niveau: str, classe: str | None) -> list[str]:
    """The part's position on the validation ladder, as a Mermaid flowchart."""
    rang = ECHELLE.index(niveau) if niveau in ECHELLE else -1
    out = ["```mermaid", "flowchart LR"]
    for i, etape in enumerate(ECHELLE):
        out.append(f'    L{i}["{etape}"]')
    out.append("    " + " --> ".join(f"L{i}" for i in range(len(ECHELLE))))
    if classe == "prohibited_pending_engineering" and rang >= 0 and rang + 1 < len(ECHELLE):
        out += ['    X["⛔ prohibited pending engineering"]',
                f"    L{rang} -. blocked .-> X"]
    out += ["    classDef here fill:#fff4d6,stroke:#b7791f,color:#1a1a1a,stroke-width:3px;",
            "    classDef done fill:#e3f1e6,stroke:#2e7d32,color:#1a1a1a;",
            "    classDef todo fill:#f4f4f4,stroke:#9e9e9e,color:#6b6b6b;",
            "    classDef stop fill:#fde2e1,stroke:#c0392b,color:#1a1a1a;"]
    for i in range(len(ECHELLE)):
        etat = "here" if i == rang else ("done" if i < rang else "todo")
        out.append(f"    class L{i} {etat}")
    if any(l.startswith("    X[") for l in out):
        out.append("    class X stop")
    return out + ["```", "",
                  f"*Validation ladder of `catalog/schemas/part.schema.json`; this record is at "
                  f"`{niveau}`.*", ""]


def page_markdown(fiche: dict, chemin_fiche: Path) -> str:
    part_id = fiche["part_id"]
    page = PAGES / f"{part_id.lower()}.md"
    classification = fiche.get("classification", {})
    fabrication = fiche.get("manufacturing", {})
    matiere = fabrication.get("material", {})
    geometrie = fiche.get("geometry", {})
    provenance = fiche.get("provenance", {})
    titane = fiche.get("titanium", {})
    validation = fiche.get("validation", {})
    statut = STATUTS.get(classification.get("safety_class"), classification.get("safety_class", "unknown"))
    procede = fabrication.get("preferred_process", "unknown")

    out = [ENTETE, "", f"# {fiche['name']}", "",
           f"**Status: {statut}. No part is released; see [SAFETY.md]({lien(ROOT / 'SAFETY.md', page)}).**", "",
           fiche.get("description", "").strip(), ""]
    out += echelle(validation.get("status", "concept"), classification.get("safety_class"))
    out += [f"Catalogue record: [`{chemin_fiche.relative_to(ROOT).as_posix()}`]({lien(chemin_fiche, page)})", ""]

    out += ["## Identity", ""]
    vehicule = fiche.get("vehicle", {})
    annees = vehicule.get("model_years", {})
    out += tableau(page, [
        ("identifier", part_id),
        ("generation", vehicule.get("generation")),
        ("variants", vehicule.get("variants")),
        ("model years", f"{annees.get('from')} to {annees.get('to')}" if annees else None),
        ("Porsche part numbers", vehicule.get("porsche_part_numbers")),
        ("category", classification.get("category")),
        ("safety class", classification.get("safety_class")),
        ("intended use", classification.get("intended_use")),
    ])

    out += ["## Material and manufacturing", ""]
    out += tableau(page, [
        ("preferred process", PROCEDES.get(procede, procede)),
        ("candidate processes", fabrication.get("candidate_processes")),
        ("material family", matiere.get("family")),
        ("grade", matiere.get("grade")),
        ("standard", matiere.get("standard")),
        ("supplier requirements", fabrication.get("supplier_requirements")),
        ("post-processing", fabrication.get("post_processing")),
    ])
    if titane.get("applicable"):
        out += ["**Titanium**", ""]
        out += tableau(page, [
            ("alloy", titane.get("alloy")),
            ("heat treatment", titane.get("heat_treatment")),
            ("HIP", titane.get("hip_required")),
            ("machined surfaces", titane.get("machined_surfaces")),
            ("inspection", titane.get("inspection")),
            ("galvanic isolation", titane.get("galvanic_isolation")),
            ("fatigue assumptions", titane.get("fatigue_assumptions")),
        ])

    out += ["## Geometry", ""]
    out += tableau(page, [
        ("source type", geometrie.get("source_type")),
        ("master format", geometrie.get("master_format")),
        ("units", geometrie.get("units")),
        ("accuracy (mm)", geometrie.get("accuracy_mm")),
    ])
    maitre = geometrie.get("master_file")
    out += fichiers(page, [maitre] if maitre else [], "Master file")
    out += fichiers(page, geometrie.get("derived_files") or [], "Derived files")

    out += images(part_id, page)

    out += ["## Provenance and sources", ""]
    out += tableau(page, [("record license", provenance.get("record_license"))])
    sources = provenance.get("sources") or []
    if sources:
        out += ["**Sources**", ""]
        for s in sources:
            titre = s.get("title") or s.get("id") or "source"
            url = s.get("url")
            note = s.get("note") or s.get("access") or ""
            ligne = f"- [{titre}]({url})" if url else f"- {titre}"
            out.append(f"{ligne}{' — ' + str(note) if note else ''}")
        out.append("")

    out += ["## Validation", ""]
    out += tableau(page, [
        ("status", validation.get("status")),
        ("vehicle tested", validation.get("vehicle_tested")),
        ("reviewed by", validation.get("reviewed_by")),
        ("limitations", validation.get("limitations") or validation.get("notes")),
    ])
    out += fichiers(page, validation.get("evidence") or [], "Evidence")

    out += dossiers_lies(part_id, page)

    out += ["---", "",
            "*Page generated from the catalogue record by `scripts/render_part_pages.py`, "
            "checked by `make check`. Corrections go in the record, not here.*", ""]
    return "\n".join(out)


def attendues() -> dict[Path, str]:
    return {PAGES / f"{json.loads(c.read_text(encoding='utf-8'))['part_id'].lower()}.md":
            page_markdown(json.loads(c.read_text(encoding="utf-8")), c)
            for c in sorted(FICHES.glob("*.json"))}


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()

    pages = attendues()
    if a.write:
        PAGES.mkdir(parents=True, exist_ok=True)
        ecrites = 0
        for chemin, texte in pages.items():
            if not chemin.exists() or chemin.read_text(encoding="utf-8") != texte:
                chemin.write_text(texte, encoding="utf-8")
                ecrites += 1
        for orpheline in sorted(PAGES.glob("*.md")):
            if orpheline not in pages:
                orpheline.unlink()
                print(f"orphan page removed: {orpheline.relative_to(ROOT)}")
        print(f"docs/pieces  {len(pages)} pages, {ecrites} rewritten")
        return 0

    manquantes = [c for c in pages if not c.exists()]
    derivees = [c for c, t in pages.items() if c.exists() and c.read_text(encoding="utf-8") != t]
    orphelines = [p for p in sorted(PAGES.glob("*.md")) if p not in pages] if PAGES.is_dir() else []
    if manquantes or derivees or orphelines:
        for chemin in manquantes:
            print(f"FAIL   missing page: {chemin.relative_to(ROOT)}", file=sys.stderr)
        for chemin in derivees:
            print(f"FAIL   page differs from its record: {chemin.relative_to(ROOT)}", file=sys.stderr)
        for chemin in orphelines:
            print(f"FAIL   page without a record: {chemin.relative_to(ROOT)}", file=sys.stderr)
        print("       rerun: python3 scripts/render_part_pages.py --write", file=sys.stderr)
        return 1
    print(f"OK   docs/pieces, {len(pages)} pages match the catalogue records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
