#!/usr/bin/env python3
"""Render docs/reports/README.md, the dated index of execution and audit reports.

`docs/reports/` holds close to a hundred dated reports, named by topic and date.
Opening the directory showed a wall of file names; this index groups them by
day, gives each its title, and charts how many were written when. It is
generated so it cannot miss a report or keep one that was removed.

    python3 scripts/render_reports_index.py --write   # rewrite the index
    python3 scripts/render_reports_index.py --check   # fail if it has drifted

A report's date is taken from its file name (`_YYYYMMDD` or `-YYYY-MM-DD`);
a report without one is listed under "undated", never given a guessed date.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "docs" / "reports"
INDEX = REPORTS / "README.md"
HEADER = "<!-- generated by scripts/render_reports_index.py - do not edit by hand -->"

DATE = re.compile(r"(20\d\d)-?([01]\d)-?([0-3]\d)")
def title(path: Path) -> str:
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("# "):
            return line[2:].strip().replace("|", "\\|")
    return path.stem


def when(path: Path) -> date | None:
    m = DATE.search(path.stem)
    if not m:
        return None
    try:
        return date(int(m[1]), int(m[2]), int(m[3]))
    except ValueError:
        return None


def render() -> str:
    reports = sorted(p for p in REPORTS.glob("*.md") if p.name != "README.md")
    by_day: dict[date | None, list[Path]] = defaultdict(list)
    for p in reports:
        by_day[when(p)].append(p)
    days = sorted(d for d in by_day if d is not None)

    out = [HEADER, "", "# Execution and audit reports", "",
           f"{len(reports)} reports of runs, audits and checkpoints, newest first"
           f"{f' ({len(by_day[None])} undated, listed last)' if by_day.get(None) else ''}. "
           "A report records what was run and what it found on that day; later work may "
           "have superseded it. Nothing here releases a part — see [SAFETY.md](../../SAFETY.md).",
           ""]
    if days:
        labels = ", ".join(f'"{d:%m-%d}"' for d in days)
        counts = ", ".join(str(len(by_day[d])) for d in days)
        top = max(len(by_day[d]) for d in days)
        out += ["```mermaid", "xychart-beta",
                f'    title "Reports written per day, {days[0]:%Y}"',
                f"    x-axis [{labels}]",
                f'    y-axis "reports" 0 --> {top + 1}',
                f"    bar [{counts}]", "```", ""]

    for d in reversed(days):
        out += [f"## {d:%B} {d.day}, {d:%Y}", "", "| report | file |", "|---|---|"]
        for p in by_day[d]:
            out.append(f"| {title(p)} | [`{p.name}`]({p.name}) |")
        out.append("")
    if by_day.get(None):
        out += ["## Undated", "", "| report | file |", "|---|---|"]
        for p in by_day[None]:
            out.append(f"| {title(p)} | [`{p.name}`]({p.name}) |")
        out.append("")
    out += ["---", "",
            "*Index generated by `scripts/render_reports_index.py`, checked by `make check`.*", ""]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()
    expected = render()
    current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
    if a.write:
        if current != expected:
            INDEX.write_text(expected, encoding="utf-8")
            print("docs/reports/README.md  rewritten")
        else:
            print("docs/reports/README.md  already up to date")
        return 0
    if current != expected:
        print("FAIL   docs/reports/README.md no longer matches docs/reports/.\n"
              "       rerun: python3 scripts/render_reports_index.py --write", file=sys.stderr)
        return 1
    print("OK   docs/reports/README.md matches the reports")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
