**
!benchmarks/
!benchmarks/openfoam-poiseuille-f25/
!benchmarks/openfoam-poiseuille-f25/**
!containers/
!containers/engine-cycle-f33.requirements.txt
!containers/917-f47-cfd-cae/
!containers/917-f47-cfd-cae/**
