<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>M64EngineLayout</AssemblyName>
    <RootNamespace>M64DigitalTwin</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PicoGK" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="/opt/picogk-binding/PicoGKBinding.csproj" />
  </ItemGroup>
</Project>
